services:
  foodtracker:
    extends:
      file: docker-compose.yaml
      service: foodtracker
    build:
      dockerfile: Dockerfile.local
    volumes:
      - ./src:/app/src
    ports:
      - 5173:5173
      - 9229:9229
    labels:
      - traefik.http.services.food-tracker.loadbalancer.server.port=5173
  foodtrackerdb:
    extends:
      file: docker-compose.yaml
      service: foodtrackerdb
volumes:
  foodtrackerdb:
  pgadmin:
networks:
  traefik:
    external: true
    name: traefik
  foodtracker:
