services:
  foodtracker:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.services.food-tracker.loadbalancer.server.port=3000
      - traefik.http.routers.food-tracker.rule=Host("tracker.dlugoschvincent.de") || Host("localhost")
      - traefik.http.routers.food-tracker.entrypoints=websecure
      - traefik.docker.network=traefik
    networks:
      - traefik
      - foodtracker
    depends_on:
      foodtrackerdb:
        condition: service_healthy

  foodtrackerdb:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: foodtracker
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - foodtrackerdb:/data/postgres -U postgres
    networks:
      - foodtracker
    healthcheck:
      test: su - postgres -c pg_isready
      interval: 5s
      timeout: 10s
      retries: 120

volumes:
  foodtrackerdb:

networks:
  traefik:
    external: true
    name: traefik
  foodtracker:
